name: emulator_checker
description: A plugin to check if app is running at an Emulator or not.
version: 1.0.0
homepage: https://github.com/rhylvin2022/emulator_checker
# repository: https://github.com/rhylvin2022/emulator_checker


environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  get_radio_version_plugin: ^1.0.0
  device_info_plus: ^4.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
